_core:
  default_config_hash: PxCy_AhIauxwM99rpXYPZme_Qs0LuevxTmbqG2dZJDA
langcode: en
recent_items: 10
hide_non_content_items: 1
show_account_link: ''
enhance_content_item: 1
show_categories_item: 1
show_media_item: 1
show_webforms_item: 1
